In [1]:
# tensorflow 
import tensorflow as tf
tf.__version__

'2.3.0'

In [2]:
import keras 
keras.__version__

'2.4.3'

In [3]:
import gensim
gensim.__version__  

ModuleNotFoundError: No module named 'gensim'

In [4]:
import sklearn
sklearn.__version__

ModuleNotFoundError: No module named 'sklearn'

In [5]:
import nltk
nltk.__version__

ModuleNotFoundError: No module named 'nltk'

In [6]:
nltk.download('treebank')

NameError: name 'nltk' is not defined

In [7]:
import pandas as pd
pd.__version__

'1.1.1'

In [8]:
# Series
sr = pd.Series([17000, 18000, 1000, 5000], index=["Pizza", "Chicken", "Coke", "Beer"])
print(sr.index)
print(sr.values)
print(sr)

Index(['Pizza', 'Chicken', 'Coke', 'Beer'], dtype='object')
[17000 18000  1000  5000]
Pizza      17000
Chicken    18000
Coke        1000
Beer        5000
dtype: int64


In [9]:
# DataFrame
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','three']
columns = ['A','B','C']
df = pd.DataFrame(values, index=index, columns=columns)
print(df.index)
print(df.columns)
print(df.values)
print(df)

Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [10]:
# Create DataFrame from list
data = [
  ['1000', 'Steve', 90.70],
  ['1001', 'James', 78.09],
  ['1002', 'Doyeon', 97.12],
  ['1003', 'Jane', 45.44],
  ['1004', 'Pilwoong', 68.12],
  ['1005', 'Tony', 88.82]
]
df = pd.DataFrame(data)
print(df)

0         1      2
0  1000     Steve  90.70
1  1001     James  78.09
2  1002    Doyeon  97.12
3  1003      Jane  45.44
4  1004  Pilwoong  68.12
5  1005      Tony  88.82


In [11]:
# Column setting in the created DataFrame
df.columns = ["num", "name", "grade"]
print(df)

num      name  grade
0  1000     Steve  90.70
1  1001     James  78.09
2  1002    Doyeon  97.12
3  1003      Jane  45.44
4  1004  Pilwoong  68.12
5  1005      Tony  88.82


In [12]:
# Index setting in the created DataFrame
df.index = 'One,Two,Three,Four,Five,Six'.split(',')
print(df)

num      name  grade
One    1000     Steve  90.70
Two    1001     James  78.09
Three  1002    Doyeon  97.12
Four   1003      Jane  45.44
Five   1004  Pilwoong  68.12
Six    1005      Tony  88.82


In [13]:
# Create

In [14]:
#Initialize column and index when credating DataFrame
index = 'One,Two,Three,Four,Five,Six'.split(',')
columns = ["num", "name", "grade"]
df2 = pd.DataFrame(data, index=df.index, columns=df.columns)
print(df2)

num      name  grade
One    1000     Steve  90.70
Two    1001     James  78.09
Three  1002    Doyeon  97.12
Four   1003      Jane  45.44
Five   1004  Pilwoong  68.12
Six    1005      Tony  88.82


In [15]:
# Create DataFrame from dictionary
columns = ["num", "name", "grade"]
datas = [['1000','1010','1020','1030','1040','1050'],
         ['Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         [10, 30, 40, 30, 20, 50]
]
data = dict(zip(columns, datas))
df = pd.DataFrame(data)
print(df)

num      name  grade
0  1000     Steve     10
1  1010     James     30
2  1020    Doyeon     40
3  1030      Jane     30
4  1040  Pilwoong     20
5  1050      Tony     50


In [16]:
# Searching DataFrame
df.head(3)

num    name  grade
0  1000   Steve     10
1  1010   James     30
2  1020  Doyeon     40

In [17]:
df.tail(3)

num      name  grade
3  1030      Jane     30
4  1040  Pilwoong     20
5  1050      Tony     50

In [18]:
print(df['num'])

0    1000
1    1010
2    1020
3    1030
4    1040
5    1050
Name: num, dtype: object


In [19]:
califonia_train_df=pd.read_csv('/content/sample_data/california_housing_train.csv')
#califonia_test_df=pd.read.csv('/content/sample_data/california_housing_test.csv')
df.index

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/california_housing_train.csv'

In [20]:
# Numpy
import numpy as np
np.__version__

'1.18.5'

In [21]:
print("Index :", index)
a = np.array(index)
print(type(a))
print(a)

Index : ['One', 'Two', 'Three', 'Four', 'Five', 'Six']
<class 'numpy.ndarray'>
['One' 'Two' 'Three' 'Four' 'Five' 'Six']


In [22]:
b = np.array([[1,2,3], [4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [23]:
print(b.ndim) # 차원 출력
print(b.shape) # 크기 출력

2
(2, 3)


In [24]:
# Initialize ndarray
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
a = np.ones((2,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
a = np.full((2,2,), 7)
print(a)

[[7 7]
 [7 7]]


In [27]:
a = np.eye(5) # 대각선으로 1 나머지 0인 2차원 배열
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
a = np.random.random((3,3)) # 랜덤
print(a)

[[0.28107076 0.53784717 0.37003479]
 [0.37504525 0.57404359 0.22313635]
 [0.59151189 0.08621485 0.50875714]]


In [29]:
# 지정된 범위에 대해 배열 생성
a = np.arange(10)
print(a) 

[0 1 2 3 4 5 6 7 8 9]


In [30]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


In [31]:
# 배열 차원 변환
# 인자의 개수와 reshape의 총크기는 동일해야한다.
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [32]:
# Numpy 슬라이싱
b = a[2:4,3:6]
print(b)

[[15 16 17]
 [21 22 23]]


In [33]:
print(a[0,:])

[0 1 2 3 4 5]


In [34]:
print(a[:,-1])

[ 5 11 17 23 29]


In [35]:
print(a[[1,2,3],[2,3,4]])

[ 8 15 22]


In [36]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)
print(x/y)
print(x%y)
print(x*y)
print(x&y)
print(x|y)
print(x^y)
print(x**y)
print(x>>y)
print(x<<y)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 2 3]
[ 4 10 18]
[0 0 2]
[5 7 7]
[5 7 5]
[  1  32 729]
[0 0 0]
[ 16  64 192]


In [37]:
# 행렬 연산을 위해서는 dot 함수를 이용
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(x,y)
print(c)
c = np.dot(a,b)
print(c)

32
[[19 22]
 [43 50]]


In [38]:
from matplotlib import pyplot as plt
plt.plot([1,2,3,4],[2,4,8,6])
plt.show()

AttributeError: module 'matplotlib' has no attribute 'pyplot'

In [39]:
# 축 레이블 삽입
plt.title('test')
plt.xlabel('hours')
plt.ylabel('score')
plt.plot([1,2,3,4],[2,4,8,6])
plt.show()

NameError: name 'plt' is not defined

In [40]:
# 라인 추가 및 범례 삽입
# 축 레이블 삽입
plt.title('test')
plt.xlabel('hours')
plt.ylabel('score')
plt.plot([1,2,3,4],[2,4,8,6])
plt.plot([1.5,2.5,3.5,4.5], [3,5,9,2])
plt.legend(['A Student', 'B Student'])
plt.show()

NameError: name 'plt' is not defined